name: more_moda_admin
description: "Admin panel"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '^3.4.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.5.3
  go_router: ^14.1.1
  get: ^4.6.6
  google_mlkit_pose_detection: ^0.13.0
  google_fonts: ^6.2.0
  get_storage: ^2.1.1
  form_field_validator: ^1.1.0
  flutter_dot: ^0.0.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.1.2
  rich_text_controller: ^2.0.1
  html_editor_enhanced: ^2.6.0
  http: ^1.2.2
  path_provider: ^2.1.3
  image_picker_for_web: ^3.0.4
  fancy_button_flutter: ^1.0.3+1
  card_loading: ^0.3.2
  awesome_snackbar_content: ^0.1.1
  collection: ^1.18.0
  http_parser: ^4.0.2
  js: ^0.7.1
  leak_tracker: ^10.0.4
  leak_tracker_flutter_testing: ^3.0.3
  material_color_utilities: ^0.11.1
  meta: ^1.12.0
  rxdart: ^0.28.0
  string_scanner: ^1.2.0
  test_api: ^0.7.0
  vm_service: ^14.2.1
  web: ^1.1.0
  web_socket_channel: ^3.0.1
  app_links: ^6.3.0
  infinite_scroll_pagination: ^4.0.0
  dropdown_search: ^6.0.1
  package_info_plus: ^8.0.2
  file_picker: ^8.1.6
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/
    - .env
